### ISSUE TITLE
کرش کردن در بعضی دستگاه ها

### ISSUE THREAD

**Issue by hamedjj** [congenialmobile/TrivialDrive#1]
بعضی موقع پیش میاد که سیستم پرداخت را درست پیاده سازی کردیم و بر روی دستگاه های مختلف امتحان کردیم و برنامه را منتشر میکنیم و عده زیادی از کاربران برنامه را دانلود و خرید میکنند و مشکلی براشون پیش نمیاد . اما بعضی موقع برای بعضی از کاربران پرداخت انجام و پول از حساب فرد کسر میشه اما بعد از برگشت به برنامه کرش به وجود میاد و برنامه آپدیت نمیشه و کاربر هر بار که برای چک کردن وضعیت خود به بازار متصل میشه همین مشکل تکرار میشه.

این مشکل در یکی از برنامه های من به وجود آمد که برنامه من بالای 2000 تا خرید شد اما 4 نفر پیام دادن که برنامه را خریداری کردیم اما برنامه آپدیت نشد و هر بار هر که وصل به بازار وصل میشوند همین وضعیت به وجود میاید.
من در انجمن برنامه نویسی اندروید این موضوع را بیان کردم و دیدم برای چند توسعه دهنده دیگر این اتفاق افتاده است

حالا الان که در حال پیاده سازی و تست بر روی امولاتور جنی موشن بودم یه اتفاق مشابه رخ داد 
پرداخت بر روی امولاتور ورژن 2.3 و 4.2.2 به درستی انجام میشه اما بر روی ورژن 4.4.2 دیالاگ پرداخت بالا میاد و در هنگام لود شدن آن کرش به وجود میاد و در بعضی مواقع صفحه پرداخت کامل بالا میاد و پرداخت انجام میشه اما موقع آپدیت برنامه کرش به وجود میاد
خطایی که رخ میدهد این است : 
Error purchasing: Iabresult : null data in IAB Result (response:1002:bad response received)

در اینترنت سرچ کردم اما مثل اینکه هنوز جوابی برای این مشکل پیدا نشده که فقط یک نفر گفت من این مشکل را در فراگمنت داشتم و وقتی پرداخت را در اکتیویتی قرار دادم این مشکل حل شد که جواب این نیست
http://stackoverflow.com/questions/16393747/

من فکر میکنم مشکل این قضیه ای که تعریف کردم همین خطا باشه و اگر جوابی برای این خطا پیدا بشه قطعا این مشکل حل میشود.
با تشکر و احترام

**Comment by hirbodk** [comment]
همانطور که می‌دانید
 `IabHelper`
یک کمک‌کننده برای استفاده از 
API 
پرداخت‌ درون‌برنامه‌ای است و کارش صرفا راحت‌تر کردن گفت‌وگو‌های برنامه‌ٔ شما با پرداخت است و نمی‌توان از آن انتظار داشت که به چیز‌هایی مثل 
`null`
شدن برخی اشیاء را در نظر گیرد. به همین علت پیشنهاد می‌شود که از همن کمک‌کننده استفاده کنید، اما تمام اشکلات احتمالی را خودتان در نظر بگیرید و با دست‌بردن در کد کمک‌کننده رسیدگی به آنها را بهبود بخشید. همچنین اکیدا توصیه می‌شود که ملاحظات امنیتی‌ای که در مستندات به آنها اشاره شده را پیاده سازی کنید.

**Comment by Booyaka-619** [comment]
Give "Start in background" permission to Bazaar app and it will solve your problem.
