### ISSUE TITLE
درخواست پرداخت به طرز نادرستی فراخوانی شده است

### ISSUE THREAD

**Issue by MJafarMashhadi** [congenialmobile/TrivialDrive#4]
No logcat messages, no exceptions. just this prompt...
![nmfxkntoah](https://cloud.githubusercontent.com/assets/3872947/6546827/7238008a-c5d8-11e4-98d8-e6053e096ea9.PNG)

**Comment by MJafarMashhadi** [comment]
Updated caffe bazaar to version 6.2, same issue

![gfvnh](https://cloud.githubusercontent.com/assets/3872947/6551553/7eb82cfa-c64f-11e4-9d4b-b8eb22f4a1cc.PNG)

**Comment by hirbodk** [comment]
این پیام هنگامی نمایش داده می‌شود که درخواست شما از سرور پرداخت معتبر نباشد، اما برای اتفاقی که در نسخهٔ جدید افتاده، خواهشمندم «شناسهٔ دستگاه» خودتون رو در بازار برای ما بفرستید تا بتوانیم مساله رو بررسی کنیم. برای یافتن شناسه کافیه تو بخش «تنظیمات» بازار، «درباره» رو انتخاب کنید و در پایین صفحه روی «شناسهٔ دستگاه شما» تپ کنید تا کپی شود.
با تشکر

**Comment by MJafarMashhadi** [comment]
oTHCmrPFTDCxSU0SUdYrEA

**Comment by hirbodk** [comment]
مشکل شما در پیاده‌سازی پرداخت است، در بازار هنگامی که درخواست خرید از سوی شما دریافت می‌شود،
CallingPackage = null
است و این باعث می‌شود تا بازار نتواند بررسی امنیتی قبل از پرداخت را انجام دهد.  بررسی‌ای که نمی‌گذاری برنامه‌های دیگر درخواست پرداخت با برنامهٔ شما را بفررستند. لطفا با مطالعهٔ مستندات پرداخت درون‌برنامه‌ایو مستندات مربوط به
getCallingPackage
در اندروید اشکال پیاده‌سازی خود را بیابید.

با تشکر
